# Generated by Django 2.1.15 on 2023-07-31 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id_bank', models.AutoField(primary_key=True, serialize=False)),
                ('institution', models.TextField(max_length=255)),
                ('debt_value', models.FloatField()),
                ('credit_value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id_monthly_expense', models.AutoField(primary_key=True, serialize=False)),
                ('payment_type', models.TextField(max_length=12)),
                ('total_value', models.FloatField()),
                ('purchase_date', models.DateField()),
                ('bank', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='polls.Bank')),
            ],
        ),
        migrations.RenameField(
            model_name='purchasecategory',
            old_name='id',
            new_name='id_purchase_category',
        ),
        migrations.AddField(
            model_name='purchase',
            name='purchase_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.PurchaseCategory'),
        ),
    ]
