# Generated by Django 2.1.15 on 2023-07-31 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20230731_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='credit_value',
        ),
        migrations.RemoveField(
            model_name='bank',
            name='debt_value',
        ),
    ]
