# Generated by Django 2.1.15 on 2023-08-01 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20230731_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='product',
            field=models.TextField(default='teste', max_length=255),
            preserve_default=False,
        ),
    ]
