# Generated by Django 4.2.3 on 2023-08-07 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_purchase_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='id_monthly_expense',
            new_name='id_purchase',
        ),
    ]
