# Generated by Django 4.2.3 on 2023-08-07 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_rename_id_monthly_expense_purchase_id_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.bank'),
        ),
    ]
