# Generated by Django 4.2.3 on 2023-08-17 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_alter_purchase_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='credit_total_value',
            field=models.FloatField(default=123),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bank',
            name='debt_total_value',
            field=models.FloatField(default='123'),
            preserve_default=False,
        ),
    ]
