# Generated by Django 4.2.5 on 2023-09-26 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_bank_credit_total_value_bank_debt_total_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id_profile', models.AutoField(primary_key=True, serialize=False)),
                ('profile_name', models.TextField(default='Luis', max_length=255)),
            ],
        ),
    ]
