# Generated by Django 4.2.9 on 2024-01-15 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.profile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_name',
            field=models.CharField(max_length=255),
        ),
    ]
