# Generated by Django 2.2.12 on 2023-07-20 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.TextField(max_length=255)),
                ('teste', models.TextField(max_length=255)),
            ],
        ),
    ]
