# Generated by Django 2.2.12 on 2023-07-20 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_finance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasecategory',
            name='teste',
        ),
    ]
